apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
data:
  PORT: "3000"
  IMAGE_URL: "https://picsum.photos/800/600"
  IMAGE_CACHE_PATH: "/cache/image.jpg"
  IMAGE_CACHE_TTL_MS: "600000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: fajouianas/devops-with-kubernetes:1.12
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: project-config
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: image-cache
              mountPath: /cache
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: shared-storage-claim
