apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: todo-backend-config
data:
  PORT: "3000"
  MAX_TODO_LENGTH: "140"
  MAX_REQUEST_BODY_LENGTH: "10000"
  PGHOST: todo-postgres-svc
  PGPORT: "5432"
  PGDATABASE: todos
  PGUSER: todo_backend
  RANDOM_ARTICLE_URL: "https://en.wikipedia.org/wiki/Special:Random"
  TODO_BACKEND_URL: "http://todo-backend-svc:2345/todos"
  HTTP_REQUEST_TIMEOUT_MS: "10000"
  RANDOM_ARTICLE_ATTEMPTS: "5"
