apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-postgres-svc
spec:
  clusterIP: None
  selector:
    app: todo-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
