apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: todo-backend-db-secret
type: Opaque
data:
    PGPASSWORD: ENC[AES256_GCM,data:9l64Sho7oTeSLjtOCyB8+aEnUhg=,iv:U3YsQQtRggapeDtWwh5xxHC9oHcWMdgs2VHbAWhPyHM=,tag:JTWgOTfAdlNF5NAte6CEYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RWcyVjBNVzdUbW40dFI2
            RDl4a2lsNjk2Y3UzdktKVWdqMTFKVTVyY1VNCmw3OXVvaHJaOURGQ0hVN0t1NVRN
            ZFRqa09BWTY3NWtob2hTY3BJV3Avb0UKLS0tIGdZNktwckU5Z0d4elE1MFpoNFZL
            VXFHNlVIRll6c0o2VlN3QWVoemhrejgKQJqfAxUdhfE1LOFenHI98lky5mYkH/XR
            apWApfHK3NgnaSGHJhrgoPAiBRhZ3vF7+B7sarem7PYzgRsCUo8Tyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1060vgm4yy7wuv73v6zn3y78k0uu9hnyxqz8ezqjxzsan7kq7ud6s97wlfa
    encrypted_regex: ^(data)$
    lastmodified: "2026-09-20T02:03:19Z"
    mac: ENC[AES256_GCM,data:2UP2QkXEoVedaOVV9uV3quD1TtItTLu+lk/1shsIVepGji39+tiCohBJcCYc0qHa4Qft9mlkcqjnKGtv8QjbhsDe8zhArG2ZttJ1Scx4PL8ks2FKcEMZi1Zd0lnrHwNi0U6hPasoxZFcdTKTsXsEKJ2w0jXVvhz5LWWGrmKFWgc=,iv:PO5y925mmenbubLHMKbOTDDBsxGhcbbWHdHWWn+pMCM=,tag:vuziVOEdA5TJKcDSuXYesA==,type:str]
    version: 3.13.3
