apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: todo-backend-db-secret
type: Opaque
data:
    PGPASSWORD: ENC[AES256_GCM,data:9l64Sho7oTeSLjtOCyB8+aEnUhg=,iv:U3YsQQtRggapeDtWwh5xxHC9oHcWMdgs2VHbAWhPyHM=,tag:JTWgOTfAdlNF5NAte6CEYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOWZ4T1ZBYlpQUHBHcjBK
            c1J3Z3JSUUI2RXU3SlM0R0I3NnFkeGFUMFdVClBHeURTNndqclJZTXA5bUhsaDBL
            UWxxMzc3SlVKYUhoLyt1Q3hNWlh5cmcKLS0tIHBRSlZ5dE1sbmlJMFUwOC8ycVFJ
            cHNkUEwvaHFqOXFWS1FielArZW5jdFkKUX6rzvFP9Lrm0nsYh/2TdL61eDML0JTO
            +WHgQOB6m+JaCMTAYrdnh4+7GMDBvhcK10dQcYfpSoD1Q/UWkeGp/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1060vgm4yy7wuv73v6zn3y78k0uu9hnyxqz8ezqjxzsan7kq7ud6s97wlfa
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTUM2SlpWTjE1YTd4RXdZ
            WkFxOFczUy9uOG1hK3ZET0JzdHY5V3VFSVVNCnJLZFY5TU5HeGJQOGJrLy9OdjZI
            ZG8zL2krQ2NqRWl4Sk5lK3ZYNmNHdkUKLS0tIFo2dkdhY3VSZ1hxNjRKRVhycGNW
            b1lKSmdaTjRUMnhHR2lFaUgwWXF4L0kKRDW3dkFxvmaEPw0MbQYLaP8B7H3rWhCD
            3SMYdl1284JRh0JxQgRyFiFwVlZXRlLtoe4pD9883EyVIV5EOVm3ZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ry0nxy4tt5xyjt6jvt3a23c7h7gr5n5rcclw9uzp5gmmg47vds5sfqk34m
    encrypted_regex: ^(data)$
    lastmodified: "2026-09-20T02:03:19Z"
    mac: ENC[AES256_GCM,data:2UP2QkXEoVedaOVV9uV3quD1TtItTLu+lk/1shsIVepGji39+tiCohBJcCYc0qHa4Qft9mlkcqjnKGtv8QjbhsDe8zhArG2ZttJ1Scx4PL8ks2FKcEMZi1Zd0lnrHwNi0U6hPasoxZFcdTKTsXsEKJ2w0jXVvhz5LWWGrmKFWgc=,iv:PO5y925mmenbubLHMKbOTDDBsxGhcbbWHdHWWn+pMCM=,tag:vuziVOEdA5TJKcDSuXYesA==,type:str]
    version: 3.13.3
