apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: fajouianas/devops-with-kubernetes:1.11-pingpong
          imagePullPolicy: Always
          env:
            - name: PING_PONG_COUNT_FILE
              value: /shared/ping-pong-count.txt
          volumeMounts:
            - name: shared-storage
              mountPath: /shared
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-storage-claim
