apiVersion: v1
kind: Secret
metadata:
    namespace: exercises
    name: ping-pong-db-secret
type: Opaque
data:
    PGPASSWORD: ENC[AES256_GCM,data:eAvnLA6sDAAdWpNW8XH1ww==,iv:YoNYmecicO9Qvk1555ZiOB50RaJ3N35GOHfcfPgpIls=,tag:tU0FIc7zdlHvLLqklK3YPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZzc1ZnFlQVU2TnE5eHgz
            MEYwbnpHTHhxTkk1QXRPUlFSdnBRTElHVVE4ClJxSFZPZWJPNWlsU0c4U0twODV4
            RUp0dHM0L2dHUUpheFpWNzVNWUJJYzQKLS0tIDl4NlNSTkY2QmhnTmhZenN0bURC
            U3UvcDZsUlJ0bHhUTVdQVnlhYS9jalUKQ+5S8iYLQuun4CE3ZmMEiJ/68XsL6Zz5
            KzkRRuptxb68haEF0fW3AhEQkc4zTWTvidwFdbu820diQhUz2EdjZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1060vgm4yy7wuv73v6zn3y78k0uu9hnyxqz8ezqjxzsan7kq7ud6s97wlfa
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZS9vQ2NjTE94T2IvbmlD
            eWpNdkRJWVltYXB4R1EwU3FSM3RTME9FTGtnClJRd2xIcFBkRXNoaFRDUHV5RmY3
            WU0wc01EdTFFanhqMWV5S1htZkg2RFUKLS0tIGNLdlhoU3dBT1l2MGE2YmtPNjFM
            UURZRkNQUmRZMEE5OGV0emZ6Z0FuUHMKlwNB5SyXLUGRGWZHH1dHZsGD5ZNZRgKh
            dinvGPtmm4p0xWAkyEP0IPpNT/z9e/tPakRuyRqr+oc3tEc2doR+mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ry0nxy4tt5xyjt6jvt3a23c7h7gr5n5rcclw9uzp5gmmg47vds5sfqk34m
    encrypted_regex: ^(data)$
    lastmodified: "2026-09-18T22:20:06Z"
    mac: ENC[AES256_GCM,data:hd92iaHIFzK6kpG4eZ5jK43UR2N9XfIdutEyGG/FVtm82cNEH+PeU4CqSJOjxd9z/if8KsEVc2V9GHkrvRpi8j4WJGE9sKllg18/DgoJ2c72Xq7i+W8/ZJ07ByI3LUUupl+Ltc8m2rDhkTA8rzAbrbym/n+z5riD4snrofMB31w=,iv:+vLOqZq5HVkSkkcPgIWWCvG57Ti/jFm6xcUApgWCiAE=,tag:P5197aUGi6sWBYsiqf2r6w==,type:str]
    version: 3.13.3
