apiVersion: v1
kind: Secret
metadata:
    namespace: exercises
    name: ping-pong-db-secret
type: Opaque
data:
    PGPASSWORD: ENC[AES256_GCM,data:eAvnLA6sDAAdWpNW8XH1ww==,iv:YoNYmecicO9Qvk1555ZiOB50RaJ3N35GOHfcfPgpIls=,tag:tU0FIc7zdlHvLLqklK3YPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTE1vYjdvWUU1cDlvRGhM
            cldOUEFVZTVhT0RGYld1YUNFczJ3NXdBZTJzCllwK3g0c0orMHdHb0oyMUpxeFJY
            Z2RsazhURHE3YXVFOWVTaWQzQUFGZmcKLS0tIGlQbTkyTWIrSmY1UmUxb3diY1NS
            czNXWnYxb05PWHdJQ2xaQWFxTnVvRGsKTIuVA0Y14glAnr8gLUXDdly7XHSrXOm4
            HLw1TjPUKcLFWkxGc3jHbYiDKpRWWPdAUEcB88/G6Jko8yIPixyGtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1060vgm4yy7wuv73v6zn3y78k0uu9hnyxqz8ezqjxzsan7kq7ud6s97wlfa
    encrypted_regex: ^(data)$
    lastmodified: "2026-09-18T22:20:06Z"
    mac: ENC[AES256_GCM,data:hd92iaHIFzK6kpG4eZ5jK43UR2N9XfIdutEyGG/FVtm82cNEH+PeU4CqSJOjxd9z/if8KsEVc2V9GHkrvRpi8j4WJGE9sKllg18/DgoJ2c72Xq7i+W8/ZJ07ByI3LUUupl+Ltc8m2rDhkTA8rzAbrbym/n+z5riD4snrofMB31w=,iv:+vLOqZq5HVkSkkcPgIWWCvG57Ti/jFm6xcUApgWCiAE=,tag:P5197aUGi6sWBYsiqf2r6w==,type:str]
    version: 3.13.3
