apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outputlogger
  template:
    metadata:
      labels:
        app: outputlogger
    spec:
      containers:
        - name: output-writer
          image: fajouianas/devops-with-kubernetes:2.01-writer
          imagePullPolicy: Always
          env:
            - name: LOG_FILE_PATH
              value: /shared/output.log
          volumeMounts:
            - name: shared-logs
              mountPath: /shared
        - name: output-reader
          image: fajouianas/devops-with-kubernetes:2.01-reader
          imagePullPolicy: Always
          env:
            - name: LOG_FILE_PATH
              value: /shared/output.log
            - name: PING_PONG_URL
              value: http://ping-pong-svc:2345/pings
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-logs
              mountPath: /shared
      volumes:
        - name: shared-logs
          emptyDir: {}
